/*******************************************************************************
 SISTEMA INTEGRAL GREEN TECH METRICS - UTN
 MODULO 1: NÚCLEO INSTITUCIONAL (ESTRUCTURA FÍSICA Y GEOGRÁFICA)
 *******************************************************************************/
-- 1. UNIVERSIDADES
CREATE TABLE universidades (
    id_universidad NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255) NOT NULL,
    siglas VARCHAR2(20),
    sitio_web VARCHAR2(255),
    logo_url VARCHAR2(500),
    pais VARCHAR2(100) DEFAULT 'Ecuador',
    ciudad_principal VARCHAR2(100),
    fecha_fundacion DATE,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP
);

COMMENT ON TABLE universidades IS 'Registro maestro de la institución educativa. Es la entidad raíz de la jerarquía organizacional.';

-- 2. CAMPUS (Sedes o Extensiones)
CREATE TABLE campus (
    id_campus NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_universidad NUMBER NOT NULL REFERENCES universidades(id_universidad),
    nombre VARCHAR2(255) NOT NULL,
    direccion VARCHAR2(500),
    latitud NUMBER(10, 8),
    longitud NUMBER(11, 8),
    area_total_m2 NUMBER(15, 2) NOT NULL,
    area_bosque_m2 NUMBER(15, 2) DEFAULT 0,
    area_edificada_m2 NUMBER(15, 2) DEFAULT 0,
    clima_tipo VARCHAR2(50),
    -- [CÁLCULO AUTOMÁTICO]: Ratio de área verde (Indicador SI2)
    porcentaje_area_verde GENERATED ALWAYS AS (
        ROUND(
            (area_bosque_m2 / NULLIF(area_total_m2, 0)) * 100,
            2
        )
    ) VIRTUAL,
    -- [CÁLCULO AUTOMÁTICO]: Área de absorción (Indicador SI4)
    area_absorcion_m2 GENERATED ALWAYS AS (
        area_total_m2 - area_edificada_m2
    ) VIRTUAL,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE campus IS 'Datos físicos del campus con cálculos automáticos de ratios de áreas verdes y absorción.';

-- 3. EDIFICIOS
CREATE TABLE edificios (
    id_edificio NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    nombre VARCHAR2(255) NOT NULL,
    codigo_interno VARCHAR2(50) UNIQUE,
    pisos NUMBER(2) DEFAULT 1,
    area_planta_m2 NUMBER(15, 2) NOT NULL,
    -- [CÁLCULO AUTOMÁTICO]: Suma de todas las plantas (Indicador SI1)
    -- Multiplica el área de la huella (planta) por el número de niveles.
    area_total_m2 GENERATED ALWAYS AS (area_planta_m2 * pisos) VIRTUAL,
    anio_construccion NUMBER(4),
    es_inteligente CHAR(1) DEFAULT 'N' CHECK (es_inteligente IN ('S', 'N')),
    estado_conservacion VARCHAR2(50),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE edificios IS 'Desglose individual de las construcciones. El área total se calcula automáticamente según plantas y niveles.';

-- 4. AREAS (Departamentos, Laboratorios, Aulas)
CREATE TABLE areas (
    id_area NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_edificio NUMBER NOT NULL REFERENCES edificios(id_edificio),
    nombre VARCHAR2(255) NOT NULL,
    tipo_area VARCHAR2(100),
    -- Administrativa, Académica, Laboratorio, Espacio Verde
    capacidad_personas NUMBER(6),
    piso_ubicacion NUMBER(2),
    area_m2 NUMBER(10, 2),
    observaciones VARCHAR2(500),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE areas IS 'Unidad mínima de división física. Fundamental para el cálculo de densidades poblacionales y distribución de recursos.';

-- Trigger para actualización de fechas
CREATE
OR REPLACE TRIGGER tr_univ_upd BEFORE
UPDATE
    ON universidades FOR EACH ROW BEGIN :NEW.actualizado_el := CURRENT_TIMESTAMP;

END;

/ 


COMMIT;

/*******************************************************************************
 SISTEMA INTEGRAL GREEN TECH METRICS - UTN
 MODULO II: MODELO DE EVALUACIÓN Y VERSIONAMIENTO (UI GREENMETRIC)
 *******************************************************************************/
-- 10. VERSIONES_EVALUACION
CREATE TABLE versiones_evaluacion (
    id_version NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    -- Ej: "UI GreenMetric Guideline 2024"
    anio_referencia NUMBER(4) NOT NULL,
    es_activa CHAR(1) DEFAULT 'N',
    normativa_url VARCHAR2(500),
    -- Link al PDF oficial de la guía
    notas_cambio CLOB,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_version_activa CHECK (es_activa IN ('S', 'N'))
);

COMMENT ON TABLE versiones_evaluacion IS 'Controla las diferentes ediciones de las guías oficiales de UI GreenMetric. Permite que el sistema soporte cambios en los criterios a través de los años sin perder datos históricos.';

-- 8. ESCALAS_EVALUACION
CREATE TABLE escalas_evaluacion (
    id_escala NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_indicador NUMBER NOT NULL REFERENCES indicadores(id_indicador),
    id_version NUMBER NOT NULL REFERENCES versiones_evaluacion(id_version),
    tipo_escala VARCHAR2(50),
    -- Ej: 'Porcentaje', 'Cantidad', 'Opciones Binarias'
    descripcion VARCHAR2(500),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE escalas_evaluacion IS 'Define la lógica de medición para un indicador específico dentro de una versión determinada del ranking.';

-- 9. RANGOS_EVALUACION
CREATE TABLE rangos_evaluacion (
    id_rango NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_escala NUMBER NOT NULL REFERENCES escalas_evaluacion(id_escala),
    nivel NUMBER(1) NOT NULL,
    -- Ej: 1, 2, 3, 4, 5
    valor_minimo NUMBER(15, 2),
    valor_maximo NUMBER(15, 2),
    descripcion VARCHAR2(500),
    -- Ej: "> 50% de energía renovable"
    puntaje_asignado NUMBER(10, 2) NOT NULL,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_nivel_rango CHECK (
        nivel BETWEEN 1
        AND 5
    )
);

COMMENT ON TABLE rangos_evaluacion IS 'Desglose detallado de los niveles de puntaje (1-5). Es el motor de cálculo que determina cuántos puntos obtiene la UTN según el dato ingresado.';

-- 5. PERIODOS (Optimización de la tabla existente para vincularla a versiones)
-- Nota: Si ya tienes la tabla, este script añade la relación necesaria.
ALTER TABLE
    periodos
ADD
    id_version NUMBER REFERENCES versiones_evaluacion(id_version);

COMMENT ON COLUMN periodos.id_version IS 'Vincula un año de evaluación con una versión específica de la metodología UI GreenMetric.';

/*******************************************************************************
 TRIGGER: TRG_PUNTUAR_METRICA_AUTOMATICO
 DESCRIPCIÓN: Busca el puntaje en RANGOS_EVALUACION basado en el VALOR_REAL_UTN.
 *******************************************************************************/
CREATE
OR REPLACE TRIGGER trg_puntuar_metrica_auto BEFORE
INSERT
    OR
UPDATE
    OF valor_real_utn ON resultados_metricas FOR EACH ROW DECLARE v_puntaje_asignado NUMBER(10, 2) := 0;

BEGIN -- 1. Buscamos el puntaje en la tabla de rangos 
-- Relacionamos Resultados -> Métricas -> Escalas -> Rangos
SELECT
    r.puntaje_asignado INTO v_puntaje_asignado
FROM
    rangos_evaluacion r
    JOIN escalas_evaluacion e ON r.id_escala = e.id_escala
    JOIN metricas m ON e.id_indicador = m.id_indicador
WHERE
    m.id_metrica = :NEW.id_metrica
    AND :NEW.valor_real_utn BETWEEN r.valor_minimo
    AND r.valor_maximo
    AND ROWNUM = 1;

-- 2. Asignamos el puntaje calculado al campo de resultados
:NEW.puntaje_obtenido_met := v_puntaje_asignado;

EXCEPTION
WHEN NO_DATA_FOUND THEN -- Si el valor no cae en ningún rango definido, el puntaje es 0
:NEW.puntaje_obtenido_met := 0;

WHEN OTHERS THEN :NEW.puntaje_obtenido_met := 0;

END;

/
/*******************************************************************************
 PROCEDURE: PRC_CONSOLIDAR_DATOS_OPERATIVOS
 DESCRIPCIÓN: Empuja los cálculos de las tablas operativas a los resultados.
 *******************************************************************************/
CREATE
OR REPLACE PROCEDURE prc_consolidar_datos_operativos (p_periodo_id NUMBER) IS BEGIN -- EJEMPLO 1: Consolidar Área Verde (Módulo Campus)
-- SI.2: Porcentaje de área verde
FOR reg IN (
    SELECT
        id_campus,
        porcentaje_area_verde
    FROM
        campus
) LOOP -- Buscamos la métrica correspondiente y actualizamos su valor real
UPDATE
    resultados_metricas
SET
    valor_real_utn = reg.porcentaje_area_verde
WHERE
    id_periodo = p_periodo_id
    AND id_metrica = (
        SELECT
            id_metrica
        FROM
            metricas
        WHERE
            nombre_metrica LIKE '%área verde%'
            AND ROWNUM = 1
    );

END LOOP;

-- EJEMPLO 2: Consolidar Huella de Carbono (Módulo Energía)
-- EC.8: Huella de Carbono Total
FOR reg IN (
    SELECT
        id_campus,
        total_co2e
    FROM
        huellas_carbono
    WHERE
        id_periodo = p_periodo_id
) LOOP
UPDATE
    resultados_metricas
SET
    valor_real_utn = reg.total_co2e
WHERE
    id_periodo = p_periodo_id
    AND id_metrica = (
        SELECT
            id_metrica
        FROM
            metricas
        WHERE
            nombre_metrica LIKE '%huella de carbono%'
            AND ROWNUM = 1
    );

END LOOP;

COMMIT;

END;

/ 

COMMIT;

/*******************************************************************************
 SISTEMA INTEGRAL GREEN TECH METRICS - UTN
 MODULO 3: PROGRAMAS INSTITUCIONALES (POLÍTICAS Y ACCIONES)
 *******************************************************************************/
-- 12. TIPOS_PROGRAMAS
CREATE TABLE tipos_programas (
    id_tipo_programa NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL UNIQUE,
    -- Ej: Conservación, Concientización, Infraestructura
    descripcion VARCHAR2(500),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE tipos_programas IS 'Clasificación temática de los programas (Educación, Gestión de Residuos, Eficiencia Energética, etc.).';

-- 13. ESTADOS_PROGRAMAS
CREATE TABLE estados_programas (
    id_estado_prog NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL UNIQUE,
    -- Ej: Planificación, Ejecución, Suspendido, Finalizado
    descripcion VARCHAR2(255)
);

COMMENT ON TABLE estados_programas IS 'Catálogo de estados para el seguimiento del ciclo de vida de los programas institucionales.';

-- 11. PROGRAMAS
CREATE TABLE programas (
    id_programa NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_tipo_programa NUMBER NOT NULL REFERENCES tipos_programas(id_tipo_programa),
    id_estado_prog NUMBER NOT NULL REFERENCES estados_programas(id_estado_prog),
    nombre VARCHAR2(255) NOT NULL,
    descripcion CLOB,
    objetivo_general VARCHAR2(1000),
    presupuesto_estimado NUMBER(15, 2),
    fecha_inicio DATE,
    fecha_fin DATE,
    responsable_area VARCHAR2(150),
    -- Unidad administrativa a cargo
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP
);

COMMENT ON TABLE programas IS 'Registro maestro de iniciativas, políticas y proyectos de sostenibilidad de la universidad.';

-- 14. PROGRAMAS_INDICADORES (Relación N:N)
CREATE TABLE programas_indicadores (
    id_programa NUMBER NOT NULL REFERENCES programas(id_programa) ON DELETE CASCADE,
    id_indicador NUMBER NOT NULL REFERENCES indicadores(id_indicador) ON DELETE CASCADE,
    impacto_esperado VARCHAR2(500),
    -- Descripción de cómo ayuda al indicador GreenMetric
    PRIMARY KEY (id_programa, id_indicador)
);

COMMENT ON TABLE programas_indicadores IS 'Vincula las acciones institucionales con los indicadores específicos de GreenMetric que pretenden mejorar.';

-- 15. PROGRAMAS_CAMPUS (Relación N:N)
CREATE TABLE programas_campus (
    id_programa NUMBER NOT NULL REFERENCES programas(id_programa) ON DELETE CASCADE,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus) ON DELETE CASCADE,
    alcance_logrado VARCHAR2(255),
    -- Ej: "Todo el campus", "Solo facultades técnicas"
    PRIMARY KEY (id_programa, id_campus)
);

COMMENT ON TABLE programas_campus IS 'Define la cobertura geográfica de cada programa, permitiendo rastrear qué sedes están ejecutando qué políticas.';

-- Trigger para actualización de fecha en programas
CREATE
OR REPLACE TRIGGER tr_programas_upd BEFORE
UPDATE
    ON programas FOR EACH ROW BEGIN :NEW.actualizado_el := CURRENT_TIMESTAMP;

END;

/ COMMIT;

/*******************************************************************************
 SISTEMA INTEGRAL GREEN TECH METRICS - UTN
 MODULO 4.1: DATOS OPERATIVOS - POBLACIÓN UNIVERSITARIA
 *******************************************************************************/
-- 16. POBLACIONES (Censo institucional por periodo)
CREATE TABLE poblaciones (
    id_poblacion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    poblacion_total NUMBER(10) NOT NULL,
    -- Sumatoria calculada
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP,
    CONSTRAINT uk_poblacion_campus_periodo UNIQUE (id_campus, id_periodo)
);

COMMENT ON TABLE poblaciones IS 'Almacena los totales demográficos consolidados por campus y año, necesarios para el cálculo de ratios de sostenibilidad.';

-- 17. DETALLES_POBLACION (Clasificación por tipo)
CREATE TABLE detalles_poblacion (
    id_detalle_pob NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_poblacion NUMBER NOT NULL REFERENCES poblaciones(id_poblacion) ON DELETE CASCADE,
    categoria_pob VARCHAR2(50),
    -- Ej: Estudiantes, Docentes, Administrativos, Externos
    cantidad NUMBER(10) DEFAULT 0,
    descripcion VARCHAR2(255)
);

COMMENT ON TABLE detalles_poblacion IS 'Desglose detallado de la población por categorías para análisis de impacto diferenciado.';

-- 18. ESTUDIANTES (Datos específicos para métricas de Educación)
CREATE TABLE estudiantes (
    id_estudiante NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    codigo_matricula VARCHAR2(50) UNIQUE,
    facultad VARCHAR2(150),
    carrera VARCHAR2(150),
    nivel_estudio VARCHAR2(50),
    -- Ej: Pregrado, Posgrado, Educación Continua
    estado_academico VARCHAR2(20) DEFAULT 'ACTIVO',
    genero CHAR(1),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE estudiantes IS 'Registro maestro de estudiantes. Permite segmentar el impacto de los programas de sostenibilidad por área académica.';

-- 19. PERSONALES (Docentes y Administrativos)
CREATE TABLE personales (
    id_personal NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    identificacion VARCHAR2(20) UNIQUE,
    nombre_completo VARCHAR2(255),
    tipo_empleado VARCHAR2(50),
    -- Ej: Docente Tiempo Completo, Administrativo, Servicios
    departamento VARCHAR2(150),
    email_inst VARCHAR2(150),
    fecha_ingreso DATE,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE personales IS 'Registro maestro del personal de la universidad, base para calcular el ratio de publicaciones por académico.';

-- Trigger para actualización automática de la población total
CREATE
OR REPLACE TRIGGER tr_poblaciones_upd BEFORE
UPDATE
    ON poblaciones FOR EACH ROW BEGIN :NEW.actualizado_el := CURRENT_TIMESTAMP;

END;

/ COMMIT;

/*******************************************************************************
 SISTEMA INTEGRAL GREEN TECH METRICS - UTN
 MODULO 4.2: DATOS OPERATIVOS - GESTIÓN FINANCIERA (PRESUPUESTO)
 *******************************************************************************/
-- 20. PRESUPUESTOS (Presupuesto General de la Universidad)
CREATE TABLE presupuestos (
    id_presupuesto NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_universidad NUMBER NOT NULL REFERENCES universidades(id_universidad),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    monto_total_univ NUMBER(18, 2) NOT NULL,
    moneda VARCHAR2(10) DEFAULT 'USD',
    fuente_financiamiento VARCHAR2(100),
    -- Ej: Estatal, Recursos Propios, Donaciones
    fecha_aprobacion DATE,
    estado_presupuesto VARCHAR2(20) DEFAULT 'APROBADO',
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_presupuesto_periodo UNIQUE (id_universidad, id_periodo)
);

COMMENT ON TABLE presupuestos IS 'Registra el presupuesto global anual de la institución, base necesaria para calcular porcentajes de inversión en sostenibilidad.';

-- 21. PRESUPUESTOS_SOSTENIBILIDAD (Inversión específica GreenMetric)
CREATE TABLE presupuestos_sostenibilidad (
    id_presup_sost NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_presupuesto NUMBER NOT NULL REFERENCES presupuestos(id_presupuesto) ON DELETE CASCADE,
    id_categoria NUMBER NOT NULL REFERENCES categorias(id_categoria),
    monto_asignado NUMBER(15, 2) DEFAULT 0,
    monto_ejecutado NUMBER(15, 2) DEFAULT 0,
    descripcion_gasto VARCHAR2(500),
    -- Ej: Instalación de Paneles, Planta de Tratamiento
    tipo_gasto VARCHAR2(50),
    -- CAPEX (Inversión) o OPEX (Operación)
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP
);

COMMENT ON TABLE presupuestos_sostenibilidad IS 'Desglose detallado de la inversión en áreas ambientales. Permite calcular el KPI de UI GreenMetric sobre presupuesto de sostenibilidad.';

-- Trigger para control de auditoría financiera
CREATE
OR REPLACE TRIGGER tr_presup_sost_upd BEFORE
UPDATE
    ON presupuestos_sostenibilidad FOR EACH ROW BEGIN :NEW.actualizado_el := CURRENT_TIMESTAMP;

END;

/ COMMIT;

/*******************************************************************************
 SISTEMA INTEGRAL GREEN TECH METRICS - UTN
 MODULO 4.3: DATOS OPERATIVOS - ENERGÍA Y CLIMA (EC) - CORREGIDO
 *******************************************************************************/
-- 0. TABLA DE APOYO: FACTORES DE EMISIÓN (Indispensable para automatizar)
CREATE TABLE factores_emision (
    id_factor NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    fuente_energia VARCHAR2(50) NOT NULL UNIQUE,
    -- Ej: 'ELECTRICIDAD_RED', 'DIESEL', 'GLP'
    valor_factor NUMBER(10, 6) NOT NULL,
    -- Valor kg CO2 por unidad
    unidad VARCHAR2(20),
    -- Ej: 'kWh', 'Galon'
    anio_referencia NUMBER(4),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE factores_emision IS 'Catálogo de factores de conversión oficiales para el cálculo de la huella de carbono.';

-- 23. MEDIDORES_ENERGETICOS (Se mantiene igual)
CREATE TABLE medidores_energeticos (
    id_medidor NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_edificio NUMBER NOT NULL REFERENCES edificios(id_edificio),
    codigo_medidor VARCHAR2(50) UNIQUE NOT NULL,
    tipo_energia VARCHAR2(50),
    -- Ej: Red Pública, Generador, Solar
    marca_modelo VARCHAR2(100),
    fecha_instalacion DATE,
    estado VARCHAR2(20) DEFAULT 'ACTIVO',
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 22. CONSUMOS_ENERGETICOS (Se mantiene, pero lista para auditoría)
CREATE TABLE consumos_energeticos (
    id_consumo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_medidor NUMBER NOT NULL REFERENCES medidores_energeticos(id_medidor),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    mes NUMBER(2) CHECK (
        mes BETWEEN 1
        AND 12
    ),
    lectura_kwh NUMBER(15, 2) NOT NULL,
    costo_estimado NUMBER(12, 2),
    evidencia_factura_url VARCHAR2(500),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 25. FUENTES_RENOVABLES (Se mantiene igual)
CREATE TABLE fuentes_renovables (
    id_fuente_ren NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    tipo_fuente VARCHAR2(50),
    -- Ej: Solar, Eólica, Biomasa
    capacidad_kw NUMBER(10, 2),
    produccion_anual_kwh NUMBER(15, 2),
    descripcion VARCHAR2(500),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 26. EQUIPOS_EFICIENTES (Se mantiene igual)
CREATE TABLE equipos_eficientes (
    id_equipo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_edificio NUMBER NOT NULL REFERENCES edificios(id_edificio),
    tipo_equipo VARCHAR2(100),
    -- Ej: Iluminación LED
    cantidad NUMBER(10),
    porcentaje_ahorro NUMBER(5, 2),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 27. EDIFICIOS_INTELIGENTES (Se mantiene igual)
CREATE TABLE detalles_smart_building (
    id_smart_det NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_edificio NUMBER NOT NULL REFERENCES edificios(id_edificio) UNIQUE,
    automatizacion_iluminacion CHAR(1) CHECK (automatizacion_iluminacion IN ('S', 'N')),
    control_climatizacion CHAR(1) CHECK (control_climatizacion IN ('S', 'N')),
    sensores_presencia CHAR(1) CHECK (sensores_presencia IN ('S', 'N')),
    sistema_gestion_energia CHAR(1) CHECK (sistema_gestion_energia IN ('S', 'N')),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 28. HUELLAS_CARBONO (AUTOMATIZADA)
-- Mantenemos tus campos de alcances, pero el TOTAL se calcula solo.
CREATE TABLE huellas_carbono (
    id_huella NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    alcance_1 NUMBER(15, 2) DEFAULT 0,
    -- Emisiones directas
    alcance_2 NUMBER(15, 2) DEFAULT 0,
    -- Emisiones indirectas
    alcance_3 NUMBER(15, 2) DEFAULT 0,
    -- Otras indirectas
    -- [CORRECCIÓN]: Columna Virtual para evitar errores de cálculo manual.
    -- Calcula el total sumando los 3 alcances.
    total_co2e NUMBER GENERATED ALWAYS AS (alcance_1 + alcance_2 + alcance_3) VIRTUAL,
    metodologia VARCHAR2(100) DEFAULT 'GHG Protocol',
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_huella_campus_periodo UNIQUE (id_campus, id_periodo)
);

COMMENT ON COLUMN huellas_carbono.total_co2e IS 'Suma automática de los alcances 1, 2 y 3. Garantiza consistencia de datos.';

COMMIT;

/*******************************************************************************
 SISTEMA INTEGRAL GREEN TECH METRICS - UTN
 MODULO 4.4: DATOS OPERATIVOS - AGUA (WS) Y RESIDUOS (WR)
 *******************************************************************************/
-- 29. CONSUMOS_AGUA (Gestión Hídrica - WS)
CREATE TABLE consumos_agua (
    id_consumo_agua NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    consumo_m3 NUMBER(15, 2) NOT NULL,
    agua_reciclada_m3 NUMBER(15, 2) DEFAULT 0,
    -- Para indicador WS2
    fuente_suministro VARCHAR2(100),
    -- Ej: Red pública, Pozo propio, Lluvia
    evidencia_url VARCHAR2(500),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE consumos_agua IS 'Registro de consumo hídrico total y aprovechamiento de agua reciclada. Base para los indicadores WS1 y WS2.';

-- 30. AGUAS_RESIDUALES (Tratamiento)
CREATE TABLE aguas_residuales (
    id_tratamiento NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    sistema_tratamiento VARCHAR2(255),
    -- Ej: Planta de tratamiento anaerobia, Humedales
    porcentaje_tratado NUMBER(5, 2),
    -- Indicador WS3
    estado_sistema VARCHAR2(50),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE aguas_residuales IS 'Describe la capacidad y eficiencia de la universidad para tratar sus aguas grises y negras antes de verterlas.';

-- 31. RESIDUOS_ORGANICOS (WR - Waste)
CREATE TABLE residuos_organicos (
    id_res_organico NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    toneladas_gen NUMBER(10, 2),
    toneladas_compost NUMBER(10, 2),
    -- Tratamiento específico WR1
    metodo_tratamiento VARCHAR2(255),
    -- Ej: Compostaje, Biodigestor
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE residuos_organicos (WR1) IS 'Métricas de tratamiento de desechos biodegradables, usualmente provenientes de cafeterías y mantenimiento de jardines.';

-- 32. RESIDUOS_INORGANICOS (Reciclaje)
CREATE TABLE residuos_inorganicos (
    id_res_inorganico NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    tipo_residuo VARCHAR2(50),
    -- Ej: Papel, Plástico, Vidrio, Metal
    toneladas_recicladas NUMBER(10, 2),
    gestor_externo VARCHAR2(255),
    -- Empresa que retira el material
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE residuos_inorganicos (WR2) IS 'Seguimiento de programas de reciclaje institucional para materiales no biodegradables.';

-- 33. RESIDUOS_PELIGROSOS (Tóxicos y Electrónicos)
CREATE TABLE residuos_peligrosos (
    id_res_peligroso NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    categoria VARCHAR2(50),
    -- Ej: Químicos, Biológicos, Electrónicos (E-Waste)
    toneladas_gen NUMBER(10, 2),
    metodo_disposicion VARCHAR2(255),
    -- Ej: Incineración controlada, Celda de seguridad
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE residuos_peligrosos (WR3) IS 'Gestión de residuos especiales que requieren protocolos de seguridad, incluyendo laboratorios y desecho tecnológico.';

COMMIT;

/*******************************************************************************
 SISTEMA INTEGRAL GREEN TECH METRICS - UTN
 MODULO 4.5: DATOS OPERATIVOS - TRANSPORTE Y MOVILIDAD (TR)
 *******************************************************************************/
-- 34. VEHICULOS (Flota Institucional)
CREATE TABLE vehiculos (
    id_vehiculo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_universidad NUMBER NOT NULL REFERENCES universidades(id_universidad),
    placa VARCHAR2(20) UNIQUE,
    tipo_vehiculo VARCHAR2(50),
    -- Ej: Auto, Bus, Motocicleta, Camión
    tipo_motor VARCHAR2(50),
    -- Ej: Combustión, Eléctrico, Híbrido (ZEV check)
    marca_modelo VARCHAR2(100),
    anio_fabricacion NUMBER(4),
    estado VARCHAR2(20) DEFAULT 'ACTIVO',
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE vehiculos IS 'Inventario de la flota vehicular gestionada por la universidad. Clave para el ratio de vehículos de cero emisiones (ZEV).';

-- 35. INGRESOS_VEHICULARES (Censo de Tráfico Diario)
CREATE TABLE ingresos_vehiculares (
    id_ingreso NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    tipo_usuario VARCHAR2(50),
    -- Ej: Estudiantes, Personal, Visitantes
    promedio_autos_dia NUMBER(10),
    promedio_motos_dia NUMBER(10),
    metodo_conteo VARCHAR2(100),
    -- Ej: Sensores en garita, Encuesta, Estimación
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ingresos_vehiculares IS 'Registro estadístico del flujo diario de vehículos motorizados que ingresan al campus (Indicador TR1).';

-- 37. SERVICIOS_TRANSPORTE (Shuttle y Transporte Colectivo)
CREATE TABLE servicios_transporte (
    id_servicio NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    nombre_ruta VARCHAR2(255),
    capacidad_pax NUMBER(5),
    frecuencia_diaria NUMBER(5),
    es_gratuito CHAR(1) CHECK (es_gratuito IN ('S', 'N')),
    es_cero_emision CHAR(1) CHECK (es_cero_emision IN ('S', 'N')),
    -- Para indicador TR2
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE servicios_transporte IS 'Detalle de los servicios de transporte compartido (Shuttle) provistos por la institución.';

-- 36. MOVILIDADES (Infraestructura Peatonal y Ciclismo)
CREATE TABLE movilidades (
    id_movilidad NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    tipo_infra VARCHAR2(50),
    -- Ej: Ciclovía, Senda Peatonal, Parqueo Bicicletas
    extension_m NUMBER(10, 2),
    -- Longitud o cantidad según el tipo
    es_inclusivo CHAR(1) CHECK (es_inclusivo IN ('S', 'N')),
    -- Discapacitados (TR8)
    estado_mantenimiento VARCHAR2(50),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE movilidades IS 'Registro de infraestructura para movilidad no motorizada y accesibilidad universal.';

-- 38. INICIATIVAS_MOVILIDAD (Políticas de Reducción)
CREATE TABLE iniciativas_movilidad (
    id_iniciativa NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_universidad NUMBER NOT NULL REFERENCES universidades(id_universidad),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    nombre_programa VARCHAR2(255),
    -- Ej: Carpooling, Teletrabajo, Día sin Auto
    descripcion VARCHAR2(1000),
    impacto_estimado VARCHAR2(255),
    evidencia_url VARCHAR2(500),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE iniciativas_movilidad IS 'Documentación de esfuerzos institucionales para limitar el uso de vehículos privados (TR7).';

COMMIT;

/*******************************************************************************
 SISTEMA INTEGRAL GREEN TECH METRICS - UTN
 MODULO 4.6: DATOS OPERATIVOS - EDUCACIÓN Y SOCIEDAD (ED)
 *******************************************************************************/
-- 40. CURSOS (Métricas de Currículo)
CREATE TABLE cursos (
    id_curso NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_universidad NUMBER NOT NULL REFERENCES universidades(id_universidad),
    codigo_curso VARCHAR2(50) UNIQUE,
    nombre_curso VARCHAR2(255) NOT NULL,
    es_sostenibilidad CHAR(1) DEFAULT 'N' CHECK (es_sostenibilidad IN ('S', 'N')),
    -- Para indicador ED1
    descripcion_ods VARCHAR2(500),
    -- Relación con los ODS
    facultad VARCHAR2(150),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE cursos IS 'Catálogo de asignaturas. Permite filtrar el porcentaje de cursos dedicados a la sostenibilidad.';

-- 42/43. INVESTIGACIONES Y PROYECTOS (Fondos y Publicaciones)
CREATE TABLE investigaciones (
    id_investigacion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_universidad NUMBER NOT NULL REFERENCES universidades(id_universidad),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    titulo VARCHAR2(500) NOT NULL,
    monto_financiamiento NUMBER(15, 2),
    -- Para indicador ED2
    es_sostenibilidad CHAR(1) DEFAULT 'N' CHECK (es_sostenibilidad IN ('S', 'N')),
    fuente_fondos VARCHAR2(150),
    -- Internos, Nacionales, Internacionales
    estado VARCHAR2(50),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE investigaciones IS 'Registro de proyectos de investigación y sus fondos asociados. Clave para el ratio de financiamiento en sostenibilidad.';

-- 44. PUBLICACIONES (Producción Académica)
CREATE TABLE publicaciones (
    id_publicacion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_investigacion NUMBER REFERENCES investigaciones(id_investigacion),
    id_personal NUMBER NOT NULL REFERENCES personales(id_personal),
    -- Autor (Docente)
    doi VARCHAR2(100) UNIQUE,
    titulo_paper VARCHAR2(500) NOT NULL,
    revista_indexada VARCHAR2(255),
    anio_publicacion NUMBER(4),
    url_evidencia VARCHAR2(500),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE publicaciones IS 'Repositorio de artículos científicos. Base para calcular el ratio de publicaciones sobre sostenibilidad por docente (ED3).';

-- 45/46/47. EVENTOS Y ACTIVIDADES (Vida Universitaria)
CREATE TABLE eventos_sostenibilidad (
    id_evento NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    tipo_evento VARCHAR2(50),
    -- Ej: Conferencia, Taller, Actividad Estudiantil, Cultural
    nombre_evento VARCHAR2(255) NOT NULL,
    organizador VARCHAR2(150),
    -- Ej: FEUE, Dirección de Investigación
    asistentes_estimados NUMBER(6),
    fecha_realizacion DATE,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE eventos_sostenibilidad IS 'Documentación de eventos y actividades que promueven la cultura ambiental (ED4, ED5, ED8).';

-- 49. STARTUPS_SOSTENIBLES (Innovación y Emprendimiento)
CREATE TABLE startups_sostenibles (
    id_startup NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_universidad NUMBER NOT NULL REFERENCES universidades(id_universidad),
    nombre_startup VARCHAR2(255) NOT NULL,
    sector_economico VARCHAR2(100),
    -- Ej: Energía, Reciclaje, Agrotech
    descripcion_impacto CLOB,
    fecha_incubacion DATE,
    estado_actual VARCHAR2(50),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE startups_sostenibles IS 'Registro de emprendimientos con enfoque verde apoyados por la UTN (ED11).';

-- 50. GRADUADOS (Impacto en el mercado laboral)
CREATE TABLE graduados_impacto (
    id_graduado_imp NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_estudiante NUMBER NOT NULL REFERENCES estudiantes(id_estudiante),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    empresa_empleo VARCHAR2(255),
    es_empleo_verde CHAR(1) DEFAULT 'N' CHECK (es_empleo_verde IN ('S', 'N')),
    -- Para ED12
    cargo VARCHAR2(150),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE graduados_impacto IS 'Seguimiento de graduados para medir el porcentaje de inserción en "empleos verdes".';

COMMIT;

/*******************************************************************************
 PROCEDIMIENTO DE CONSOLIDACIÓN: ENERGÍA -> RESULTADOS_METRICAS
 *******************************************************************************/
CREATE
OR REPLACE PROCEDURE prc_consolidar_energia (
    p_periodo_id NUMBER,
    p_campus_id NUMBER
) IS v_total_kwh NUMBER;

v_metrica_id NUMBER;

BEGIN -- 1. Obtener el ID de la métrica correspondiente a "Consumo Eléctrico"
-- Suponiendo que el código de indicador para consumo es 'EC.4'
SELECT
    m.id_metrica INTO v_metrica_id
FROM
    metricas m
    JOIN indicadores i ON m.id_indicador = i.id_indicador
WHERE
    i.codigo_indicador = 'EC.4'
    AND ROWNUM = 1;

-- 2. Sumar el consumo de todos los medidores de ese campus en ese periodo
SELECT
    SUM(lectura_kwh) INTO v_total_kwh
FROM
    consumos_energeticos ce
    JOIN medidores_energeticos me ON ce.id_medidor = me.id_medidor
    JOIN edificios ed ON me.id_edificio = ed.id_edificio
WHERE
    ce.id_periodo = p_periodo_id
    AND ed.id_campus = p_campus_id;

-- 3. Actualizar tu tabla de resultados (Esto disparará tus triggers de cascada)
UPDATE
    resultados_metricas
SET
    valor_real_utn = v_total_kwh
WHERE
    id_metrica = v_metrica_id
    AND id_periodo = p_periodo_id;

COMMIT;

END;

/ CREATE
OR REPLACE TRIGGER trg_calcular_puntaje_metrica BEFORE
INSERT
    OR
UPDATE
    ON resultados_metricas FOR EACH ROW DECLARE v_puntaje_obtenido NUMBER(10, 2);

BEGIN -- Buscamos el puntaje en la tabla de rangos basándonos en la escala del indicador
BEGIN
SELECT
    puntaje_asignado INTO v_puntaje_obtenido
FROM
    rangos_evaluacion r
    JOIN escalas_evaluacion e ON r.id_escala = e.id_escala
    JOIN metricas m ON m.id_indicador = e.id_indicador
WHERE
    m.id_metrica = :NEW.id_metrica
    AND :NEW.valor_real_utn BETWEEN r.valor_minimo
    AND r.valor_maximo
    AND ROWNUM = 1;

-- Por si los rangos se solapan ligeramente
:NEW.puntaje_obtenido := v_puntaje_obtenido;

EXCEPTION
WHEN NO_DATA_FOUND THEN :NEW.puntaje_obtenido := 0;

-- Si el valor no entra en ningún rango
END;

END;

/ CREATE
OR REPLACE TRIGGER trg_actualizar_totales_ranking
AFTER
INSERT
    OR
UPDATE
    ON resultados_metricas FOR EACH ROW DECLARE v_id_indicador NUMBER;

v_id_categoria NUMBER;

BEGIN -- 1. Obtener la jerarquía
SELECT
    id_indicador INTO v_id_indicador
FROM
    metricas
WHERE
    id_metrica = :NEW.id_metrica;

SELECT
    id_categoria INTO v_id_categoria
FROM
    indicadores
WHERE
    id_indicador = v_id_indicador;

-- 2. Actualizar el total del Indicador (Suma de sus métricas)
UPDATE
    indicadores
SET
    puntaje_total_ind = (
        SELECT
            SUM(puntaje_obtenido)
        FROM
            resultados_metricas rm
            JOIN metricas m ON rm.id_metrica = m.id_metrica
        WHERE
            m.id_indicador = v_id_indicador
    )
WHERE
    id_indicador = v_id_indicador;

-- 3. Actualizar el total de la Categoría (Suma de sus indicadores)
UPDATE
    categorias_indicadores
SET
    puntaje_total_cat = (
        SELECT
            SUM(puntaje_total_ind)
        FROM
            indicadores
        WHERE
            id_categoria = v_id_categoria
    )
WHERE
    id_categoria = v_id_categoria;

END;

/