/*******************************************************************************
 SISTEMA INTEGRAL GREEN TECH METRICS - UTN
 MODULO I: SEGURIDAD, ROLES Y ACCESOS
 *******************************************************************************/
-- 1. ROLES
CREATE TABLE roles (
    id_rol NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL UNIQUE,
    descripcion VARCHAR2(255),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE roles IS 'Perfiles de usuario que definen el nivel de autoridad y acceso dentro del sistema Green Tech.';

COMMENT ON COLUMN roles.id_rol IS 'Identificador único autoincremental del rol.';

COMMENT ON COLUMN roles.nombre IS 'Nombre único del perfil (ej. ADMIN, EDITOR, VISOR).';

COMMENT ON COLUMN roles.descripcion IS 'Explicación detallada de las responsabilidades asociadas al rol.';

-- 2. PERMISOS
CREATE TABLE permisos (
    id_permiso NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    clave VARCHAR2(50) NOT NULL UNIQUE,
    nombre VARCHAR2(100) NOT NULL,
    area_funcional VARCHAR2(50)
);

COMMENT ON TABLE permisos IS 'Catálogo de privilegios que pueden ser controladas en el sistema.';

COMMENT ON COLUMN permisos.clave IS 'Código interno único para validaciones lógicas (ej. MOD_INFRAESTRUCTURA).';

COMMENT ON COLUMN permisos.area_funcional IS 'Módulo al que pertenece el permiso (SEGURIDAD, GESTION, REPORTES).';

-- 3. ROL_PERMISOS (Relación N:N)
CREATE TABLE rol_permisos (
    id_rol NUMBER NOT NULL REFERENCES roles(id_rol) ON DELETE CASCADE,
    id_permiso NUMBER NOT NULL REFERENCES permisos(id_permiso) ON DELETE CASCADE,
    PRIMARY KEY (id_rol, id_permiso)
);

COMMENT ON TABLE rol_permisos IS 'Tabla intermedia que vincula los roles con sus respectivos privilegios.';

-- 4. USUARIOS
CREATE TABLE usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_rol NUMBER NOT NULL REFERENCES roles(id_rol),
    username VARCHAR2(50) NOT NULL UNIQUE,
    email VARCHAR2(150) NOT NULL UNIQUE,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    estado VARCHAR2(15) DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO', 'BLOQUEADO')),
    ultimo_login TIMESTAMP,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE usuarios IS 'Registro maestro de personal autorizado para la gestión de datos de sostenibilidad.';

COMMENT ON COLUMN usuarios.password_hash IS 'Hash de contraseña almacenado con algoritmo seguro (ej. bcrypt, Argon2 o SHA-256 + salt).';

COMMENT ON COLUMN usuarios.estado IS 'Estado operativo de la cuenta para control de acceso.';

-- 5. USUARIOS_ROLES (Relación N:N)
CREATE TABLE usuarios_roles (
    id_usuario_rol NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    id_rol NUMBER NOT NULL,
    fecha_asignacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    asignado_por NUMBER,
    activo CHAR(1) DEFAULT 'S',
    -- Restricciones de Integridad
    CONSTRAINT fk_ur_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_ur_rol FOREIGN KEY (id_rol) REFERENCES roles(id_rol) ON DELETE CASCADE,
    CONSTRAINT uk_usuario_rol UNIQUE (id_usuario, id_rol),
    CONSTRAINT ck_ur_activo CHECK (activo IN ('S', 'N'))
);

COMMENT ON TABLE usuarios_roles IS 'Tabla intermedia para la asignación dinámica de roles a usuarios. Permite un modelo de seguridad multi-rol.';

COMMENT ON COLUMN usuarios_roles.asignado_por IS 'Referencia al usuario que realizó la asignación del rol.';

COMMIT;

-- 6. LOGS_ACCESO
CREATE TABLE logs_acceso (
    id_log NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL REFERENCES usuarios(id_usuario),
    evento VARCHAR2(100),
    ip_address VARCHAR2(45),
    user_agent VARCHAR2(255),
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE logs_acceso IS 'Registro histórico de eventos de autenticación para auditoría de seguridad.';

COMMENT ON COLUMN logs_acceso.evento IS 'Descripción del suceso (ej. LOGIN_EXITOSO, INTENTO_FALLIDO).';

COMMENT ON COLUMN logs_acceso.ip_address IS 'Dirección IP desde la cual se realizó la petición (soporta IPv4 e IPv6).';

/*******************************************************************************
 SISTEMA INTEGRAL GREEN TECH METRICS - UTN
 MÓDULO II: ESTRUCTURA ESTRATÉGICA BASE
 *******************************************************************************/
--- 1. CATEGORÍAS UI GREENMETRIC
CREATE TABLE categorias (
    id_categoria NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    codigo_ref VARCHAR2(10) NOT NULL UNIQUE,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(1000),
    peso_porcentaje NUMBER(5, 2) NOT NULL,
    puntaje_maximo NUMBER(10, 2) NOT NULL,
    color_hex VARCHAR2(7),
    orden_visual NUMBER(2)
);

COMMENT ON TABLE categorias IS 'Catálogo maestro de categorías del ranking UI GreenMetric.
Define los pilares estratégicos de evaluación institucional.';

--- 2. INDICADORES UI GREENMETRIC
CREATE TABLE indicadores (
    id_indicador NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_categoria NUMBER NOT NULL REFERENCES categorias(id_categoria),
    codigo_indicador VARCHAR2(20) NOT NULL UNIQUE,
    nombre VARCHAR2(255) NOT NULL,
    descripcion CLOB,
    puntaje_maximo NUMBER(10, 2) NOT NULL,
    estado VARCHAR2(15) DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

COMMENT ON TABLE indicadores IS 'Catálogo maestro de indicadores UI GreenMetric.
Representa los criterios específicos de evaluación por categoría.';

--- 3. ODS
CREATE TABLE ods (
    id_ods NUMBER PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(500)
);

COMMENT ON TABLE ods IS 'Catálogo oficial de los Objetivos de Desarrollo Sostenible definidos por la ONU.';

COMMENT ON COLUMN ods.id_ods IS 'Identificador oficial del ODS (1 al 17).';

--- 4. INDICADORES_ODS (Relación N:N)
CREATE TABLE indicadores_ods (
    id_indicador NUMBER NOT NULL REFERENCES indicadores(id_indicador) ON DELETE CASCADE,
    id_ods NUMBER NOT NULL REFERENCES ods(id_ods) ON DELETE CASCADE,
    PRIMARY KEY (id_indicador, id_ods)
);

COMMENT ON TABLE indicadores_ods IS 'Tabla de relación que vincula los indicadores UI GreenMetric
con los Objetivos de Desarrollo Sostenible impactados.';

-- 5. PERIODOS DE EVALUACIÓN UI GREENMETRIC
CREATE TABLE periodos (
    id_periodo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    anio NUMBER(4) NOT NULL UNIQUE,
    nombre VARCHAR2(50),
    descripcion VARCHAR2(255),
    estado VARCHAR2(15) DEFAULT 'ABIERTO' CHECK (
        estado IN ('ABIERTO', 'EN_EVALUACION', 'CERRADO')
    ),
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE,
    fecha_cierre DATE,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE periodos IS 'Representa cada edición anual del proceso de evaluación UI GreenMetric.
Permite gestionar resultados históricos, cierres oficiales y rankings por año.';

COMMENT ON COLUMN periodos.anio IS 'Año calendario de la evaluación (ej. 2024, 2025).';

COMMENT ON COLUMN periodos.estado IS 'Estado del periodo dentro del ciclo de evaluación:
ABIERTO (configuración),
EN_EVALUACION (registro activo),
CERRADO (resultados finales publicados).';

COMMENT ON COLUMN periodos.fecha_cierre IS 'Fecha en la que el periodo se cierra oficialmente y no admite modificaciones.';

-- 6. MÉTRICAS UI GREENMETRIC POR PERIODO
CREATE TABLE metricas (
    id_metrica NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_indicador NUMBER NOT NULL REFERENCES indicadores(id_indicador),
    nombre_metrica VARCHAR2(255) NOT NULL,
    criterio_evaluacion CLOB,
    unidad_medida VARCHAR2(50),
    puntaje_max_met NUMBER(10, 2) NOT NULL,
    visible CHAR(1) DEFAULT 'S' CHECK (visible IN ('S', 'N')),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP,
    CONSTRAINT uk_metrica UNIQUE (id_indicador, nombre_metrica)
);

COMMENT ON TABLE metricas IS 'Catálogo estático de métricas UI GreenMetric. Define las métricas
asociadas a cada indicador, independientes del periodo de evaluación.';

/*******************************************************************************
 SISTEMA INTEGRAL GREEN TECH METRICS - UTN
 MÓDULO II: RESULTADOS Y EVALUACIONES POR PERÍODO
 *******************************************************************************/
-- 1. RESULTADOS CATEGORIAS
CREATE TABLE resultados_categorias (
    id_resultado_cat NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_categoria NUMBER NOT NULL REFERENCES categorias(id_categoria),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    puntaje_maximo NUMBER(10, 2) NOT NULL,
    puntaje_obtenido NUMBER(10, 2) DEFAULT 0,
    porcentaje_logro NUMBER(5, 2),
    posicion_nacional NUMBER,
    posicion_global NUMBER,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_cat_periodo UNIQUE (id_categoria, id_periodo)
);

COMMENT ON TABLE resultados_categorias IS 'Almacena los resultados obtenidos por la universidad en cada categoría
del ranking UI GreenMetric por periodo de evaluación.';

--- 2. RESULTADOS INDICADORES 
CREATE TABLE resultados_indicadores (
    id_resultado_ind NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_indicador NUMBER NOT NULL REFERENCES indicadores(id_indicador),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    puntaje_maximo NUMBER(10, 2) NOT NULL,
    puntaje_obtenido NUMBER(10, 2) DEFAULT 0,
    porcentaje_logro NUMBER(5, 2),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ind_periodo UNIQUE (id_indicador, id_periodo)
);

COMMENT ON TABLE resultados_indicadores IS 'Registra los resultados obtenidos en cada indicador del ranking
UI GreenMetric por periodo de evaluación.';

-- 3. ESTADO EVALUACION METRICAS
CREATE TABLE estados_evaluacion (
    id_estado NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    codigo VARCHAR2(20) NOT NULL UNIQUE,
    nombre VARCHAR2(50) NOT NULL,
    descripcion VARCHAR2(255)
);

COMMENT ON TABLE estados_evaluacion IS 'Catálogo de estados del proceso de evaluación de métricas UI GreenMetric, 
controla el ciclo de vida de evaluación de métricas por periodo.';

COMMENT ON COLUMN estados_evaluacion.codigo IS 'Código lógico del estado (BORRADOR, VALIDADA, OBSERVADA, CERRADA).';

--- 4. RESULTADOS METRICAS
CREATE TABLE resultados_metricas (
    id_resultado_met NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_metrica NUMBER NOT NULL REFERENCES metricas(id_metrica),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    id_estado NUMBER DEFAULT 1 NOT NULL REFERENCES estados_evaluacion(id_estado),
    valor_real_utn NUMBER(15, 2) DEFAULT 0,
    puntaje_obtenido_met NUMBER(10, 2) DEFAULT 0,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP,
    CONSTRAINT chk_puntaje_resultado CHECK (puntaje_obtenido_met >= 0),
    CONSTRAINT uk_metrica_periodo UNIQUE (id_metrica, id_periodo)
);

COMMENT ON TABLE resultados_metricas IS 'Registra los valores reales y puntajes obtenidos de cada métrica
UI GreenMetric por periodo de evaluación.';

--- 5. RESULTADOS GENERALES
CREATE TABLE resultados_generales (
    id_resultado_gen NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    puntaje_total NUMBER(10, 2),
    posicion_nacional NUMBER,
    posicion_global NUMBER,
    total_universidades NUMBER,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_resultado_periodo UNIQUE (id_periodo)
);

COMMENT ON TABLE resultados_generales IS 'Resultado consolidado del desempeño institucional de la universidad
en el ranking UI GreenMetric por periodo.';

/*******************************************************************************
 SISTEMA INTEGRAL GREEN TECH METRICS - UTN
 MODULO 1: NÚCLEO INSTITUCIONAL (ESTRUCTURA FÍSICA Y GEOGRÁFICA)
 *******************************************************************************/
-- 1. UNIVERSIDADES
CREATE TABLE universidades (
    id_universidad NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255) NOT NULL,
    siglas VARCHAR2(20),
    sitio_web VARCHAR2(255),
    logo_url VARCHAR2(500),
    pais VARCHAR2(100) DEFAULT 'Ecuador',
    ciudad_principal VARCHAR2(100),
    fecha_fundacion DATE,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP
);

COMMENT ON TABLE universidades IS 'Registro maestro de la institución educativa. Es la entidad raíz de la jerarquía organizacional.';

-- 2. CAMPUS (Sedes o Extensiones)
CREATE TABLE campus (
    id_campus NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_universidad NUMBER NOT NULL REFERENCES universidades(id_universidad),
    nombre VARCHAR2(255) NOT NULL,
    direccion VARCHAR2(500),
    latitud NUMBER(10, 8),
    longitud NUMBER(11, 8),
    area_total_m2 NUMBER(15, 2) NOT NULL,
    area_bosque_m2 NUMBER(15, 2) DEFAULT 0,
    area_edificada_m2 NUMBER(15, 2) DEFAULT 0,
    clima_tipo VARCHAR2(50),
    -- [CÁLCULO AUTOMÁTICO]: Ratio de área verde (Indicador SI2)
    porcentaje_area_verde GENERATED ALWAYS AS (
        ROUND(
            (area_bosque_m2 / NULLIF(area_total_m2, 0)) * 100,
            2
        )
    ) VIRTUAL,
    -- [CÁLCULO AUTOMÁTICO]: Área de absorción (Indicador SI4)
    area_absorcion_m2 GENERATED ALWAYS AS (
        area_total_m2 - area_edificada_m2
    ) VIRTUAL,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE campus IS 'Datos físicos del campus con cálculos automáticos de ratios de áreas verdes y absorción.';

-- 3. EDIFICIOS
CREATE TABLE edificios (
    id_edificio NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    nombre VARCHAR2(255) NOT NULL,
    codigo_interno VARCHAR2(50) UNIQUE,
    pisos NUMBER(2) DEFAULT 1,
    area_planta_m2 NUMBER(15, 2) NOT NULL,
    -- [CÁLCULO AUTOMÁTICO]: Suma de todas las plantas (Indicador SI1)
    -- Multiplica el área de la huella (planta) por el número de niveles.
    area_total_m2 GENERATED ALWAYS AS (area_planta_m2 * pisos) VIRTUAL,
    anio_construccion NUMBER(4),
    es_inteligente CHAR(1) DEFAULT 'N' CHECK (es_inteligente IN ('S', 'N')),
    estado_conservacion VARCHAR2(50),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE edificios IS 'Desglose individual de las construcciones. El área total se calcula automáticamente según plantas y niveles.';

-- 4. AREAS (Departamentos, Laboratorios, Aulas)
CREATE TABLE areas (
    id_area NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_edificio NUMBER NOT NULL REFERENCES edificios(id_edificio),
    nombre VARCHAR2(255) NOT NULL,
    tipo_area VARCHAR2(100),
    -- Administrativa, Académica, Laboratorio, Espacio Verde
    capacidad_personas NUMBER(6),
    piso_ubicacion NUMBER(2),
    area_m2 NUMBER(10, 2),
    observaciones VARCHAR2(500),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE areas IS 'Unidad mínima de división física. Fundamental para el cálculo de densidades poblacionales y distribución de recursos.';

COMMIT;

/*******************************************************************************
 SISTEMA INTEGRAL GREEN TECH METRICS - UTN
 MODULO II: MODELO DE EVALUACIÓN Y VERSIONAMIENTO (UI GREENMETRIC)
 *******************************************************************************/
-- 10. VERSIONES_EVALUACION
CREATE TABLE versiones_evaluacion (
    id_version NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    -- Ej: "UI GreenMetric Guideline 2024"
    anio_referencia NUMBER(4) NOT NULL,
    es_activa CHAR(1) DEFAULT 'N',
    normativa_url VARCHAR2(500),
    -- Link al PDF oficial de la guía
    notas_cambio CLOB,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_version_activa CHECK (es_activa IN ('S', 'N'))
);

COMMENT ON TABLE versiones_evaluacion IS 'Controla las diferentes ediciones de las guías oficiales de UI GreenMetric. Permite que el sistema soporte cambios en los criterios a través de los años sin perder datos históricos.';

-- 8. ESCALAS_EVALUACION
CREATE TABLE escalas_evaluacion (
    id_escala NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_indicador NUMBER NOT NULL REFERENCES indicadores(id_indicador),
    id_version NUMBER NOT NULL REFERENCES versiones_evaluacion(id_version),
    tipo_escala VARCHAR2(50),
    -- Ej: 'Porcentaje', 'Cantidad', 'Opciones Binarias'
    descripcion VARCHAR2(500),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE escalas_evaluacion IS 'Define la lógica de medición para un indicador específico dentro de una versión determinada del ranking.';

-- 9. RANGOS_EVALUACION
CREATE TABLE rangos_evaluacion (
    id_rango NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_escala NUMBER NOT NULL REFERENCES escalas_evaluacion(id_escala),
    nivel NUMBER(1) NOT NULL,
    -- Ej: 1, 2, 3, 4, 5
    valor_minimo NUMBER(15, 2),
    valor_maximo NUMBER(15, 2),
    descripcion VARCHAR2(500),
    -- Ej: "> 50% de energía renovable"
    puntaje_asignado NUMBER(10, 2) NOT NULL,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_nivel_rango CHECK (
        nivel BETWEEN 1
        AND 5
    )
);

COMMENT ON TABLE rangos_evaluacion IS 'Desglose detallado de los niveles de puntaje (1-5). Es el motor de cálculo que determina cuántos puntos obtiene la UTN según el dato ingresado.';

-- 5. PERIODOS (Optimización de la tabla existente para vincularla a versiones)
-- Nota: Si ya tienes la tabla, este script añade la relación necesaria.
ALTER TABLE
    periodos
ADD
    id_version NUMBER REFERENCES versiones_evaluacion(id_version);

COMMENT ON COLUMN periodos.id_version IS 'Vincula un año de evaluación con una versión específica de la metodología UI GreenMetric.';

COMMIT;

/*******************************************************************************
 SISTEMA INTEGRAL GREEN TECH METRICS - UTN
 MODULO 3: PROGRAMAS INSTITUCIONALES (POLÍTICAS Y ACCIONES)
 *******************************************************************************/
-- 12. TIPOS_PROGRAMAS
CREATE TABLE tipos_programas (
    id_tipo_programa NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL UNIQUE,
    -- Ej: Conservación, Concientización, Infraestructura
    descripcion VARCHAR2(500),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE tipos_programas IS 'Clasificación temática de los programas (Educación, Gestión de Residuos, Eficiencia Energética, etc.).';

-- 13. ESTADOS_PROGRAMAS
CREATE TABLE estados_programas (
    id_estado_prog NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL UNIQUE,
    -- Ej: Planificación, Ejecución, Suspendido, Finalizado
    descripcion VARCHAR2(255)
);

COMMENT ON TABLE estados_programas IS 'Catálogo de estados para el seguimiento del ciclo de vida de los programas institucionales.';

-- 11. PROGRAMAS
CREATE TABLE programas (
    id_programa NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_tipo_programa NUMBER NOT NULL REFERENCES tipos_programas(id_tipo_programa),
    id_estado_prog NUMBER NOT NULL REFERENCES estados_programas(id_estado_prog),
    nombre VARCHAR2(255) NOT NULL,
    descripcion CLOB,
    objetivo_general VARCHAR2(1000),
    presupuesto_estimado NUMBER(15, 2),
    fecha_inicio DATE,
    fecha_fin DATE,
    responsable_area VARCHAR2(150),
    -- Unidad administrativa a cargo
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP
);

COMMENT ON TABLE programas IS 'Registro maestro de iniciativas, políticas y proyectos de sostenibilidad de la universidad.';

-- 14. PROGRAMAS_INDICADORES (Relación N:N)
CREATE TABLE programas_indicadores (
    id_programa NUMBER NOT NULL REFERENCES programas(id_programa) ON DELETE CASCADE,
    id_indicador NUMBER NOT NULL REFERENCES indicadores(id_indicador) ON DELETE CASCADE,
    impacto_esperado VARCHAR2(500),
    -- Descripción de cómo ayuda al indicador GreenMetric
    PRIMARY KEY (id_programa, id_indicador)
);

COMMENT ON TABLE programas_indicadores IS 'Vincula las acciones institucionales con los indicadores específicos de GreenMetric que pretenden mejorar.';

-- 15. PROGRAMAS_CAMPUS (Relación N:N)
CREATE TABLE programas_campus (
    id_programa NUMBER NOT NULL REFERENCES programas(id_programa) ON DELETE CASCADE,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus) ON DELETE CASCADE,
    alcance_logrado VARCHAR2(255),
    -- Ej: "Todo el campus", "Solo facultades técnicas"
    PRIMARY KEY (id_programa, id_campus)
);

COMMENT ON TABLE programas_campus IS 'Define la cobertura geográfica de cada programa, permitiendo rastrear qué sedes están ejecutando qué políticas.';

COMMIT;

/*******************************************************************************
 SISTEMA INTEGRAL GREEN TECH METRICS - UTN
 MODULO 4.1: DATOS OPERATIVOS - POBLACIÓN UNIVERSITARIA
 *******************************************************************************/
-- 16. POBLACIONES (Censo institucional por periodo)
CREATE TABLE poblaciones (
    id_poblacion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    poblacion_total NUMBER(10) NOT NULL,
    -- Sumatoria calculada
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP,
    CONSTRAINT uk_poblacion_campus_periodo UNIQUE (id_campus, id_periodo)
);

COMMENT ON TABLE poblaciones IS 'Almacena los totales demográficos consolidados por campus y año, necesarios para el cálculo de ratios de sostenibilidad.';

-- 17. DETALLES_POBLACION (Clasificación por tipo)
CREATE TABLE detalles_poblacion (
    id_detalle_pob NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_poblacion NUMBER NOT NULL REFERENCES poblaciones(id_poblacion) ON DELETE CASCADE,
    categoria_pob VARCHAR2(50),
    -- Ej: Estudiantes, Docentes, Administrativos, Externos
    cantidad NUMBER(10) DEFAULT 0,
    descripcion VARCHAR2(255)
);

COMMENT ON TABLE detalles_poblacion IS 'Desglose detallado de la población por categorías para análisis de impacto diferenciado.';

-- 18. ESTUDIANTES (Datos específicos para métricas de Educación)
CREATE TABLE estudiantes (
    id_estudiante NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    codigo_matricula VARCHAR2(50) UNIQUE,
    facultad VARCHAR2(150),
    carrera VARCHAR2(150),
    nivel_estudio VARCHAR2(50),
    -- Ej: Pregrado, Posgrado, Educación Continua
    estado_academico VARCHAR2(20) DEFAULT 'ACTIVO',
    genero CHAR(1),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE estudiantes IS 'Registro maestro de estudiantes. Permite segmentar el impacto de los programas de sostenibilidad por área académica.';

-- 19. PERSONALES (Docentes y Administrativos)
CREATE TABLE personales (
    id_personal NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    identificacion VARCHAR2(20) UNIQUE,
    nombre_completo VARCHAR2(255),
    tipo_empleado VARCHAR2(50),
    -- Ej: Docente Tiempo Completo, Administrativo, Servicios
    departamento VARCHAR2(150),
    email_inst VARCHAR2(150),
    fecha_ingreso DATE,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE personales IS 'Registro maestro del personal de la universidad, base para calcular el ratio de publicaciones por académico.';

COMMIT;

/*******************************************************************************
 SISTEMA INTEGRAL GREEN TECH METRICS - UTN
 MODULO 4.2: DATOS OPERATIVOS - GESTIÓN FINANCIERA (PRESUPUESTO)
 *******************************************************************************/
-- 20. PRESUPUESTOS (Presupuesto General de la Universidad)
CREATE TABLE presupuestos (
    id_presupuesto NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_universidad NUMBER NOT NULL REFERENCES universidades(id_universidad),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    monto_total_univ NUMBER(18, 2) NOT NULL,
    moneda VARCHAR2(10) DEFAULT 'USD',
    fuente_financiamiento VARCHAR2(100),
    -- Ej: Estatal, Recursos Propios, Donaciones
    fecha_aprobacion DATE,
    estado_presupuesto VARCHAR2(20) DEFAULT 'APROBADO',
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_presupuesto_periodo UNIQUE (id_universidad, id_periodo)
);

COMMENT ON TABLE presupuestos IS 'Registra el presupuesto global anual de la institución, base necesaria para calcular porcentajes de inversión en sostenibilidad.';

-- 21. PRESUPUESTOS_SOSTENIBILIDAD (Inversión específica GreenMetric)
CREATE TABLE presupuestos_sostenibilidad (
    id_presup_sost NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_presupuesto NUMBER NOT NULL REFERENCES presupuestos(id_presupuesto) ON DELETE CASCADE,
    id_categoria NUMBER NOT NULL REFERENCES categorias(id_categoria),
    monto_asignado NUMBER(15, 2) DEFAULT 0,
    monto_ejecutado NUMBER(15, 2) DEFAULT 0,
    descripcion_gasto VARCHAR2(500),
    -- Ej: Instalación de Paneles, Planta de Tratamiento
    tipo_gasto VARCHAR2(50),
    -- CAPEX (Inversión) o OPEX (Operación)
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP
);

COMMENT ON TABLE presupuestos_sostenibilidad IS 'Desglose detallado de la inversión en áreas ambientales. Permite calcular el KPI de UI GreenMetric sobre presupuesto de sostenibilidad.';

COMMIT;

/*******************************************************************************
 SISTEMA INTEGRAL GREEN TECH METRICS - UTN
 MODULO 4.3: DATOS OPERATIVOS - ENERGÍA Y CLIMA (EC) - CORREGIDO
 *******************************************************************************/
-- 0. TABLA DE APOYO: FACTORES DE EMISIÓN (Indispensable para automatizar)
CREATE TABLE factores_emision (
    id_factor NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    fuente_energia VARCHAR2(50) NOT NULL UNIQUE,
    -- Ej: 'ELECTRICIDAD_RED', 'DIESEL', 'GLP'
    valor_factor NUMBER(10, 6) NOT NULL,
    -- Valor kg CO2 por unidad
    unidad VARCHAR2(20),
    -- Ej: 'kWh', 'Galon'
    anio_referencia NUMBER(4),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE factores_emision IS 'Catálogo de factores de conversión oficiales para el cálculo de la huella de carbono.';

-- 23. MEDIDORES_ENERGETICOS (Se mantiene igual)
CREATE TABLE medidores_energeticos (
    id_medidor NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_edificio NUMBER NOT NULL REFERENCES edificios(id_edificio),
    codigo_medidor VARCHAR2(50) UNIQUE NOT NULL,
    tipo_energia VARCHAR2(50),
    -- Ej: Red Pública, Generador, Solar
    marca_modelo VARCHAR2(100),
    fecha_instalacion DATE,
    estado VARCHAR2(20) DEFAULT 'ACTIVO',
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 22. CONSUMOS_ENERGETICOS (Se mantiene, pero lista para auditoría)
CREATE TABLE consumos_energeticos (
    id_consumo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_medidor NUMBER NOT NULL REFERENCES medidores_energeticos(id_medidor),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    mes NUMBER(2) CHECK (
        mes BETWEEN 1
        AND 12
    ),
    lectura_kwh NUMBER(15, 2) NOT NULL,
    costo_estimado NUMBER(12, 2),
    evidencia_factura_url VARCHAR2(500),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 25. FUENTES_RENOVABLES (Se mantiene igual)
CREATE TABLE fuentes_renovables (
    id_fuente_ren NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    tipo_fuente VARCHAR2(50),
    -- Ej: Solar, Eólica, Biomasa
    capacidad_kw NUMBER(10, 2),
    produccion_anual_kwh NUMBER(15, 2),
    descripcion VARCHAR2(500),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 26. EQUIPOS_EFICIENTES (Se mantiene igual)
CREATE TABLE equipos_eficientes (
    id_equipo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_edificio NUMBER NOT NULL REFERENCES edificios(id_edificio),
    tipo_equipo VARCHAR2(100),
    -- Ej: Iluminación LED
    cantidad NUMBER(10),
    porcentaje_ahorro NUMBER(5, 2),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 27. EDIFICIOS_INTELIGENTES (Se mantiene igual)
CREATE TABLE detalles_smart_building (
    id_smart_det NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_edificio NUMBER NOT NULL REFERENCES edificios(id_edificio) UNIQUE,
    automatizacion_iluminacion CHAR(1) CHECK (automatizacion_iluminacion IN ('S', 'N')),
    control_climatizacion CHAR(1) CHECK (control_climatizacion IN ('S', 'N')),
    sensores_presencia CHAR(1) CHECK (sensores_presencia IN ('S', 'N')),
    sistema_gestion_energia CHAR(1) CHECK (sistema_gestion_energia IN ('S', 'N')),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 28. HUELLAS_CARBONO (AUTOMATIZADA)
-- Mantenemos tus campos de alcances, pero el TOTAL se calcula solo.
CREATE TABLE huellas_carbono (
    id_huella NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    alcance_1 NUMBER(15, 2) DEFAULT 0,
    -- Emisiones directas
    alcance_2 NUMBER(15, 2) DEFAULT 0,
    -- Emisiones indirectas
    alcance_3 NUMBER(15, 2) DEFAULT 0,
    -- Otras indirectas
    -- [CORRECCIÓN]: Columna Virtual para evitar errores de cálculo manual.
    -- Calcula el total sumando los 3 alcances.
    total_co2e NUMBER GENERATED ALWAYS AS (alcance_1 + alcance_2 + alcance_3) VIRTUAL,
    metodologia VARCHAR2(100) DEFAULT 'GHG Protocol',
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_huella_campus_periodo UNIQUE (id_campus, id_periodo)
);

COMMENT ON COLUMN huellas_carbono.total_co2e IS 'Suma automática de los alcances 1, 2 y 3. Garantiza consistencia de datos.';

COMMIT;

/*******************************************************************************
 SISTEMA INTEGRAL GREEN TECH METRICS - UTN
 MODULO 4.4: DATOS OPERATIVOS - AGUA (WS) Y RESIDUOS (WR)
 *******************************************************************************/
-- 29. CONSUMOS_AGUA (Gestión Hídrica - WS)
CREATE TABLE consumos_agua (
    id_consumo_agua NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    consumo_m3 NUMBER(15, 2) NOT NULL,
    agua_reciclada_m3 NUMBER(15, 2) DEFAULT 0,
    -- Para indicador WS2
    fuente_suministro VARCHAR2(100),
    -- Ej: Red pública, Pozo propio, Lluvia
    evidencia_url VARCHAR2(500),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE consumos_agua IS 'Registro de consumo hídrico total y aprovechamiento de agua reciclada. Base para los indicadores WS1 y WS2.';

-- 30. AGUAS_RESIDUALES (Tratamiento)
CREATE TABLE aguas_residuales (
    id_tratamiento NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    sistema_tratamiento VARCHAR2(255),
    -- Ej: Planta de tratamiento anaerobia, Humedales
    porcentaje_tratado NUMBER(5, 2),
    -- Indicador WS3
    estado_sistema VARCHAR2(50),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE aguas_residuales IS 'Describe la capacidad y eficiencia de la universidad para tratar sus aguas grises y negras antes de verterlas.';

-- 31. RESIDUOS_ORGANICOS (WR - Waste)
CREATE TABLE residuos_organicos (
    id_res_organico NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    toneladas_gen NUMBER(10, 2),
    toneladas_compost NUMBER(10, 2),
    -- Tratamiento específico WR1
    metodo_tratamiento VARCHAR2(255),
    -- Ej: Compostaje, Biodigestor
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE residuos_organicos IS 'Métricas de tratamiento de desechos biodegradables, usualmente provenientes de cafeterías y mantenimiento de jardines.';

-- 32. RESIDUOS_INORGANICOS (Reciclaje)
CREATE TABLE residuos_inorganicos (
    id_res_inorganico NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    tipo_residuo VARCHAR2(50),
    -- Ej: Papel, Plástico, Vidrio, Metal
    toneladas_recicladas NUMBER(10, 2),
    gestor_externo VARCHAR2(255),
    -- Empresa que retira el material
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE residuos_inorganicos IS 'Seguimiento de programas de reciclaje institucional para materiales no biodegradables.';

-- 33. RESIDUOS_PELIGROSOS (Tóxicos y Electrónicos)
CREATE TABLE residuos_peligrosos (
    id_res_peligroso NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    categoria VARCHAR2(50),
    -- Ej: Químicos, Biológicos, Electrónicos (E-Waste)
    toneladas_gen NUMBER(10, 2),
    metodo_disposicion VARCHAR2(255),
    -- Ej: Incineración controlada, Celda de seguridad
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE residuos_peligrosos IS 'Gestión de residuos especiales que requieren protocolos de seguridad, incluyendo laboratorios y desecho tecnológico.';

COMMIT;

/*******************************************************************************
 SISTEMA INTEGRAL GREEN TECH METRICS - UTN
 MODULO 4.5: DATOS OPERATIVOS - TRANSPORTE Y MOVILIDAD (TR)
 *******************************************************************************/
-- 34. VEHICULOS (Flota Institucional)
CREATE TABLE vehiculos (
    id_vehiculo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_universidad NUMBER NOT NULL REFERENCES universidades(id_universidad),
    placa VARCHAR2(20) UNIQUE,
    tipo_vehiculo VARCHAR2(50),
    -- Ej: Auto, Bus, Motocicleta, Camión
    tipo_motor VARCHAR2(50),
    -- Ej: Combustión, Eléctrico, Híbrido (ZEV check)
    marca_modelo VARCHAR2(100),
    anio_fabricacion NUMBER(4),
    estado VARCHAR2(20) DEFAULT 'ACTIVO',
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE vehiculos IS 'Inventario de la flota vehicular gestionada por la universidad. Clave para el ratio de vehículos de cero emisiones (ZEV).';

-- 35. INGRESOS_VEHICULARES (Censo de Tráfico Diario)
CREATE TABLE ingresos_vehiculares (
    id_ingreso NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    tipo_usuario VARCHAR2(50),
    -- Ej: Estudiantes, Personal, Visitantes
    promedio_autos_dia NUMBER(10),
    promedio_motos_dia NUMBER(10),
    metodo_conteo VARCHAR2(100),
    -- Ej: Sensores en garita, Encuesta, Estimación
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE ingresos_vehiculares IS 'Registro estadístico del flujo diario de vehículos motorizados que ingresan al campus (Indicador TR1).';

-- 37. SERVICIOS_TRANSPORTE (Shuttle y Transporte Colectivo)
CREATE TABLE servicios_transporte (
    id_servicio NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    nombre_ruta VARCHAR2(255),
    capacidad_pax NUMBER(5),
    frecuencia_diaria NUMBER(5),
    es_gratuito CHAR(1) CHECK (es_gratuito IN ('S', 'N')),
    es_cero_emision CHAR(1) CHECK (es_cero_emision IN ('S', 'N')),
    -- Para indicador TR2
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE servicios_transporte IS 'Detalle de los servicios de transporte compartido (Shuttle) provistos por la institución.';

-- 36. MOVILIDADES (Infraestructura Peatonal y Ciclismo)
CREATE TABLE movilidades (
    id_movilidad NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    tipo_infra VARCHAR2(50),
    -- Ej: Ciclovía, Senda Peatonal, Parqueo Bicicletas
    extension_m NUMBER(10, 2),
    -- Longitud o cantidad según el tipo
    es_inclusivo CHAR(1) CHECK (es_inclusivo IN ('S', 'N')),
    -- Discapacitados (TR8)
    estado_mantenimiento VARCHAR2(50),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE movilidades IS 'Registro de infraestructura para movilidad no motorizada y accesibilidad universal.';

-- 38. INICIATIVAS_MOVILIDAD (Políticas de Reducción)
CREATE TABLE iniciativas_movilidad (
    id_iniciativa NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_universidad NUMBER NOT NULL REFERENCES universidades(id_universidad),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    nombre_programa VARCHAR2(255),
    -- Ej: Carpooling, Teletrabajo, Día sin Auto
    descripcion VARCHAR2(1000),
    impacto_estimado VARCHAR2(255),
    evidencia_url VARCHAR2(500),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE iniciativas_movilidad IS 'Documentación de esfuerzos institucionales para limitar el uso de vehículos privados (TR7).';

COMMIT;

/*******************************************************************************
 SISTEMA INTEGRAL GREEN TECH METRICS - UTN
 MODULO 4.6: DATOS OPERATIVOS - EDUCACIÓN Y SOCIEDAD (ED)
 *******************************************************************************/
-- 40. CURSOS (Métricas de Currículo)
CREATE TABLE cursos (
    id_curso NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_universidad NUMBER NOT NULL REFERENCES universidades(id_universidad),
    codigo_curso VARCHAR2(50) UNIQUE,
    nombre_curso VARCHAR2(255) NOT NULL,
    es_sostenibilidad CHAR(1) DEFAULT 'N' CHECK (es_sostenibilidad IN ('S', 'N')),
    -- Para indicador ED1
    descripcion_ods VARCHAR2(500),
    -- Relación con los ODS
    facultad VARCHAR2(150),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE cursos IS 'Catálogo de asignaturas. Permite filtrar el porcentaje de cursos dedicados a la sostenibilidad.';

-- 42/43. INVESTIGACIONES Y PROYECTOS (Fondos y Publicaciones)
CREATE TABLE investigaciones (
    id_investigacion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_universidad NUMBER NOT NULL REFERENCES universidades(id_universidad),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    titulo VARCHAR2(500) NOT NULL,
    monto_financiamiento NUMBER(15, 2),
    -- Para indicador ED2
    es_sostenibilidad CHAR(1) DEFAULT 'N' CHECK (es_sostenibilidad IN ('S', 'N')),
    fuente_fondos VARCHAR2(150),
    -- Internos, Nacionales, Internacionales
    estado VARCHAR2(50),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE investigaciones IS 'Registro de proyectos de investigación y sus fondos asociados. Clave para el ratio de financiamiento en sostenibilidad.';

-- 44. PUBLICACIONES (Producción Académica)
CREATE TABLE publicaciones (
    id_publicacion NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_investigacion NUMBER REFERENCES investigaciones(id_investigacion),
    id_personal NUMBER NOT NULL REFERENCES personales(id_personal),
    -- Autor (Docente)
    doi VARCHAR2(100) UNIQUE,
    titulo_paper VARCHAR2(500) NOT NULL,
    revista_indexada VARCHAR2(255),
    anio_publicacion NUMBER(4),
    url_evidencia VARCHAR2(500),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE publicaciones IS 'Repositorio de artículos científicos. Base para calcular el ratio de publicaciones sobre sostenibilidad por docente (ED3).';

-- 45/46/47. EVENTOS Y ACTIVIDADES (Vida Universitaria)
CREATE TABLE eventos_sostenibilidad (
    id_evento NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_campus NUMBER NOT NULL REFERENCES campus(id_campus),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    tipo_evento VARCHAR2(50),
    -- Ej: Conferencia, Taller, Actividad Estudiantil, Cultural
    nombre_evento VARCHAR2(255) NOT NULL,
    organizador VARCHAR2(150),
    -- Ej: FEUE, Dirección de Investigación
    asistentes_estimados NUMBER(6),
    fecha_realizacion DATE,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE eventos_sostenibilidad IS 'Documentación de eventos y actividades que promueven la cultura ambiental (ED4, ED5, ED8).';

-- 49. STARTUPS_SOSTENIBLES (Innovación y Emprendimiento)
CREATE TABLE startups_sostenibles (
    id_startup NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_universidad NUMBER NOT NULL REFERENCES universidades(id_universidad),
    nombre_startup VARCHAR2(255) NOT NULL,
    sector_economico VARCHAR2(100),
    -- Ej: Energía, Reciclaje, Agrotech
    descripcion_impacto CLOB,
    fecha_incubacion DATE,
    estado_actual VARCHAR2(50),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE startups_sostenibles IS 'Registro de emprendimientos con enfoque verde apoyados por la UTN (ED11).';

-- 50. GRADUADOS (Impacto en el mercado laboral)
CREATE TABLE graduados_impacto (
    id_graduado_imp NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_estudiante NUMBER NOT NULL REFERENCES estudiantes(id_estudiante),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    empresa_empleo VARCHAR2(255),
    es_empleo_verde CHAR(1) DEFAULT 'N' CHECK (es_empleo_verde IN ('S', 'N')),
    -- Para ED12
    cargo VARCHAR2(150),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE graduados_impacto IS 'Seguimiento de graduados para medir el porcentaje de inserción en "empleos verdes".';

<<<<<<< HEAD
COMMIT;


-- 51. TIPOS EVIDENCIA
CREATE TABLE tipos_evidencia (
    id_tipo_evidencia       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre                  VARCHAR2(50) NOT NULL,
    descripcion             VARCHAR2(255),
    extensiones_permitidas  VARCHAR2(100)
);

COMMENT ON TABLE tipos_evidencia IS 'Catálogo para los tipos de archivos de evidencia que se pueden subir.';

-- 52. EVIDENCIAS
CREATE TABLE evidencias (
    id_evidencia      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_tipo_evidencia NUMBER NOT NULL,
    id_resultado_met  NUMBER NOT NULL,
    id_usuario        NUMBER NOT NULL,
    nombre_archivo    VARCHAR2(200) NOT NULL,
    ruta_archivo      VARCHAR2(500),
    tamanio_archivo   NUMBER(12),
    tipo_mime         VARCHAR2(100),
    descripcion       VARCHAR2(255),
    fecha_subida      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_evid_tipo
      FOREIGN KEY (id_tipo_evidencia) REFERENCES tipos_evidencia(id_tipo_evidencia),

    CONSTRAINT fk_evid_resultado_met
      FOREIGN KEY (id_resultado_met) REFERENCES resultados_metricas(id_resultado_met),

    CONSTRAINT fk_evid_usuario
      FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
);

COMMENT ON TABLE evidencias IS 'Almacena metadatos de evidencias asociadas a resultados de métricas por período.';
