/*******************************************************************************
 SISTEMA INTEGRAL GREEN TECH METRICS - UTN
 MÓDULO II: RESULTADOS Y EVALUACIONES POR PERÍODO
 *******************************************************************************/
-- 1. RESULTADOS CATEGORIAS
CREATE TABLE resultados_categorias (
    id_resultado_cat NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_categoria NUMBER NOT NULL REFERENCES categorias(id_categoria),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    puntaje_maximo NUMBER(10, 2) NOT NULL,
    puntaje_obtenido NUMBER(10, 2) DEFAULT 0,
    porcentaje_logro NUMBER(5, 2),
    posicion_nacional NUMBER,
    posicion_global NUMBER,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_cat_periodo UNIQUE (id_categoria, id_periodo)
);

COMMENT ON TABLE resultados_categorias IS 'Almacena los resultados obtenidos por la universidad en cada categoría
del ranking UI GreenMetric por periodo de evaluación.';

--- 2. RESULTADOS INDICADORES 
CREATE TABLE resultados_indicadores (
    id_resultado_ind NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_indicador NUMBER NOT NULL REFERENCES indicadores(id_indicador),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    puntaje_maximo NUMBER(10, 2) NOT NULL,
    puntaje_obtenido NUMBER(10, 2) DEFAULT 0,
    porcentaje_logro NUMBER(5, 2),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_ind_periodo UNIQUE (id_indicador, id_periodo)
);

COMMENT ON TABLE resultados_indicadores IS 'Registra los resultados obtenidos en cada indicador del ranking
UI GreenMetric por periodo de evaluación.';

-- 3. ESTADO EVALUACION METRICAS
CREATE TABLE estados_evaluacion (
    id_estado NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    codigo VARCHAR2(20) NOT NULL UNIQUE,
    nombre VARCHAR2(50) NOT NULL,
    descripcion VARCHAR2(255)
);

COMMENT ON TABLE estados_evaluacion IS 'Catálogo de estados del proceso de evaluación de métricas UI GreenMetric, 
controla el ciclo de vida de evaluación de métricas por periodo.';

COMMENT ON COLUMN estados_evaluacion.codigo IS 'Código lógico del estado (BORRADOR, VALIDADA, OBSERVADA, CERRADA).';

--- 4. RESULTADOS METRICAS
CREATE TABLE resultados_metricas (
    id_resultado_met NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_metrica NUMBER NOT NULL REFERENCES metricas(id_metrica),
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    id_estado NUMBER DEFAULT 1 NOT NULL REFERENCES estados_evaluacion(id_estado),
    valor_real_utn NUMBER(15, 2) DEFAULT 0,
    puntaje_obtenido_met NUMBER(10, 2) DEFAULT 0,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP,
    CONSTRAINT chk_puntaje_resultado CHECK (puntaje_obtenido_met >= 0),
    CONSTRAINT uk_metrica_periodo UNIQUE (id_metrica, id_periodo)
);

COMMENT ON TABLE resultados_metricas IS 'Registra los valores reales y puntajes obtenidos de cada métrica
UI GreenMetric por periodo de evaluación.';

--- 5. RESULTADOS GENERALES
CREATE TABLE resultados_generales (
    id_resultado_gen NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_periodo NUMBER NOT NULL REFERENCES periodos(id_periodo),
    puntaje_total NUMBER(10, 2),
    posicion_nacional NUMBER,
    posicion_global NUMBER,
    total_universidades NUMBER,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_resultado_periodo UNIQUE (id_periodo)
);

COMMENT ON TABLE resultados_generales IS 'Resultado consolidado del desempeño institucional de la universidad
en el ranking UI GreenMetric por periodo.';