/*******************************************************************************
 SISTEMA INTEGRAL GREEN TECH METRICS - UTN
 MODULO I: SEGURIDAD, ROLES Y ACCESOS
 *******************************************************************************/
-- 1. ROLES
CREATE TABLE roles (
    id_rol NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL UNIQUE,
    descripcion VARCHAR2(255),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE roles IS 'Perfiles de usuario que definen el nivel de autoridad y acceso dentro del sistema Green Tech.';

COMMENT ON COLUMN roles.id_rol IS 'Identificador único autoincremental del rol.';

COMMENT ON COLUMN roles.nombre IS 'Nombre único del perfil (ej. ADMIN, EDITOR, VISOR).';

COMMENT ON COLUMN roles.descripcion IS 'Explicación detallada de las responsabilidades asociadas al rol.';

-- 2. PERMISOS
CREATE TABLE permisos (
    id_permiso NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    clave VARCHAR2(50) NOT NULL UNIQUE,
    nombre VARCHAR2(100) NOT NULL,
    area_funcional VARCHAR2(50)
);

COMMENT ON TABLE permisos IS 'Catálogo de privilegios que pueden ser controladas en el sistema.';

COMMENT ON COLUMN permisos.clave IS 'Código interno único para validaciones lógicas (ej. MOD_INFRAESTRUCTURA).';

COMMENT ON COLUMN permisos.area_funcional IS 'Módulo al que pertenece el permiso (SEGURIDAD, GESTION, REPORTES).';

-- 3. ROL_PERMISOS (Relación N:N)
CREATE TABLE rol_permisos (
    id_rol NUMBER NOT NULL REFERENCES roles(id_rol) ON DELETE CASCADE,
    id_permiso NUMBER NOT NULL REFERENCES permisos(id_permiso) ON DELETE CASCADE,
    PRIMARY KEY (id_rol, id_permiso)
);

COMMENT ON TABLE rol_permisos IS 'Tabla intermedia que vincula los roles con sus respectivos privilegios.';

-- 4. USUARIOS
CREATE TABLE usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_rol NUMBER NOT NULL REFERENCES roles(id_rol),
    username VARCHAR2(50) NOT NULL UNIQUE,
    email VARCHAR2(150) NOT NULL UNIQUE,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    estado VARCHAR2(15) DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO', 'BLOQUEADO')),
    ultimo_login TIMESTAMP,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE usuarios IS 'Registro maestro de personal autorizado para la gestión de datos de sostenibilidad.';

COMMENT ON COLUMN usuarios.password_hash IS 'Hash de contraseña almacenado con algoritmo seguro (ej. bcrypt, Argon2 o SHA-256 + salt).';

COMMENT ON COLUMN usuarios.estado IS 'Estado operativo de la cuenta para control de acceso.';

-- 5. USUARIOS_ROLES (Relación N:N)
CREATE TABLE usuarios_roles (
    id_usuario_rol  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_usuario      NUMBER NOT NULL,
    id_rol          NUMBER NOT NULL,
    fecha_asignacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    asignado_por    NUMBER, 
    activo          CHAR(1) DEFAULT 'S',
    
    -- Restricciones de Integridad
    CONSTRAINT fk_ur_usuario 
        FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    
    CONSTRAINT fk_ur_rol 
        FOREIGN KEY (id_rol) REFERENCES roles(id_rol) ON DELETE CASCADE,
        
    CONSTRAINT uk_usuario_rol 
        UNIQUE (id_usuario, id_rol),
        
    CONSTRAINT ck_ur_activo 
        CHECK (activo IN ('S', 'N'))
);

COMMENT ON TABLE usuarios_roles IS 'Tabla intermedia para la asignación dinámica de roles a usuarios. Permite un modelo de seguridad multi-rol.';
COMMENT ON COLUMN usuarios_roles.asignado_por IS 'Referencia al usuario que realizó la asignación del rol.';



COMMIT;

-- 6. LOGS_ACCESO
CREATE TABLE logs_acceso (
    id_log NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL REFERENCES usuarios(id_usuario),
    evento VARCHAR2(100),
    ip_address VARCHAR2(45),
    user_agent VARCHAR2(255),
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE logs_acceso IS 'Registro histórico de eventos de autenticación para auditoría de seguridad.';

COMMENT ON COLUMN logs_acceso.evento IS 'Descripción del suceso (ej. LOGIN_EXITOSO, INTENTO_FALLIDO).';

COMMENT ON COLUMN logs_acceso.ip_address IS 'Dirección IP desde la cual se realizó la petición (soporta IPv4 e IPv6).';


-- INSERCIÓN DE DATOS SEMILLA (SEGURIDAD)
INSERT INTO
    roles (nombre, descripcion)
VALUES
    (
        'ADMIN',
        'Administrador total del sistema y gestión de usuarios.'
    );

INSERT INTO
    roles (nombre, descripcion)
VALUES
    (
        'EDITOR',
        'Encargado de la carga técnica de métricas y evidencias.'
    );

INSERT INTO
    roles (nombre, descripcion)
VALUES
    (
        'VISOR',
        'Acceso de lectura para consultas y reportes ejecutivos.'
    );

COMMIT;