/*******************************************************************************
 SISTEMA INTEGRAL GREEN TECH METRICS - UTN
 MÓDULO II: ESTRUCTURA ESTRATÉGICA BASE
 *******************************************************************************/
--- 1. CATEGORÍAS UI GREENMETRIC
CREATE TABLE categorias (
    id_categoria NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    codigo_ref VARCHAR2(10) NOT NULL UNIQUE,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(1000),
    peso_porcentaje NUMBER(5, 2) NOT NULL,
    puntaje_maximo NUMBER(10, 2) NOT NULL,
    color_hex VARCHAR2(7),
    orden_visual NUMBER(2)
);

COMMENT ON TABLE categorias IS 'Catálogo maestro de categorías del ranking UI GreenMetric.
Define los pilares estratégicos de evaluación institucional.';

--- 2. INDICADORES UI GREENMETRIC
CREATE TABLE indicadores (
    id_indicador NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_categoria NUMBER NOT NULL REFERENCES categorias(id_categoria),
    codigo_indicador VARCHAR2(20) NOT NULL UNIQUE,
    nombre VARCHAR2(255) NOT NULL,
    descripcion CLOB,
    puntaje_maximo NUMBER(10, 2) NOT NULL,
    estado VARCHAR2(15) DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

COMMENT ON TABLE indicadores IS 'Catálogo maestro de indicadores UI GreenMetric.
Representa los criterios específicos de evaluación por categoría.';

--- 3. ODS
CREATE TABLE ods (
    id_ods NUMBER PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(500)
);

COMMENT ON TABLE ods IS 'Catálogo oficial de los Objetivos de Desarrollo Sostenible definidos por la ONU.';

COMMENT ON COLUMN ods.id_ods IS 'Identificador oficial del ODS (1 al 17).';

--- 4. INDICADORES_ODS (Relación N:N)
CREATE TABLE indicadores_ods (
    id_indicador NUMBER NOT NULL REFERENCES indicadores(id_indicador) ON DELETE CASCADE,
    id_ods NUMBER NOT NULL REFERENCES ods(id_ods) ON DELETE CASCADE,
    PRIMARY KEY (id_indicador, id_ods)
);

COMMENT ON TABLE indicadores_ods IS 'Tabla de relación que vincula los indicadores UI GreenMetric
con los Objetivos de Desarrollo Sostenible impactados.';

-- 5. PERIODOS DE EVALUACIÓN UI GREENMETRIC
CREATE TABLE periodos (
    id_periodo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    anio NUMBER(4) NOT NULL UNIQUE,
    nombre VARCHAR2(50),
    descripcion VARCHAR2(255),
    estado VARCHAR2(15) DEFAULT 'ABIERTO' CHECK (
        estado IN ('ABIERTO', 'EN_EVALUACION', 'CERRADO')
    ),
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE,
    fecha_cierre DATE,
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE periodos IS 'Representa cada edición anual del proceso de evaluación UI GreenMetric.
Permite gestionar resultados históricos, cierres oficiales y rankings por año.';

COMMENT ON COLUMN periodos.anio IS 'Año calendario de la evaluación (ej. 2024, 2025).';

COMMENT ON COLUMN periodos.estado IS 'Estado del periodo dentro del ciclo de evaluación:
ABIERTO (configuración),
EN_EVALUACION (registro activo),
CERRADO (resultados finales publicados).';

COMMENT ON COLUMN periodos.fecha_cierre IS 'Fecha en la que el periodo se cierra oficialmente y no admite modificaciones.';

-- 6. MÉTRICAS UI GREENMETRIC POR PERIODO
CREATE TABLE metricas (
    id_metrica NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_indicador NUMBER NOT NULL REFERENCES indicadores(id_indicador),
    nombre_metrica VARCHAR2(255) NOT NULL,
    criterio_evaluacion CLOB,
    unidad_medida VARCHAR2(50),
    puntaje_max_met NUMBER(10, 2) NOT NULL,
    visible CHAR(1) DEFAULT 'S' CHECK (visible IN ('S', 'N')),
    creado_el TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actualizado_el TIMESTAMP,
    CONSTRAINT uk_metrica UNIQUE (id_indicador, nombre_metrica)
);

COMMENT ON TABLE metricas IS 'Catálogo estático de métricas UI GreenMetric. Define las métricas
asociadas a cada indicador, independientes del periodo de evaluación.';